name: flutter_hackathon
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.0
  flutter_native_splash: ^2.4.5
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - lib/src/public/enemy/
    - lib/src/public/hero/
    - lib/src/public/background.jpg
    - assets/images/Logo.png
    - assets/images/Logo.png

flutter_native_splash:
  color: "#f5f5ef"
  image: "assets/images/Logo.png"
  fullscreen: true
  android_12:
    icon_background_color: "#add8e6"
    image: "assets/images/Logo.png"
    icon_background_color_dark: "#f5f5ef"
    image_dark: "assets/images/Logo.png"
