// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-2l0nH94lU539ED83WbDv9F8kWtNVEQ',
    appId: '1:472340965151:web:edc78f34fdc353021db22a',
    messagingSenderId: '472340965151',
    projectId: 'flutterhackathon-f3a03',
    authDomain: 'flutterhackathon-f3a03.firebaseapp.com',
    storageBucket: 'flutterhackathon-f3a03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAImKFwl8ePR4-qZi2ZL-wEp80XcIKlBRE',
    appId: '1:472340965151:android:6a58452b052badd31db22a',
    messagingSenderId: '472340965151',
    projectId: 'flutterhackathon-f3a03',
    storageBucket: 'flutterhackathon-f3a03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqlsoLyelvM6IDF8bk3OfZBnMJd7yb2VY',
    appId: '1:472340965151:ios:c0c0fdb3cec6613f1db22a',
    messagingSenderId: '472340965151',
    projectId: 'flutterhackathon-f3a03',
    storageBucket: 'flutterhackathon-f3a03.firebasestorage.app',
    iosBundleId: 'com.example.flutterHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqlsoLyelvM6IDF8bk3OfZBnMJd7yb2VY',
    appId: '1:472340965151:ios:c0c0fdb3cec6613f1db22a',
    messagingSenderId: '472340965151',
    projectId: 'flutterhackathon-f3a03',
    storageBucket: 'flutterhackathon-f3a03.firebasestorage.app',
    iosBundleId: 'com.example.flutterHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8-2l0nH94lU539ED83WbDv9F8kWtNVEQ',
    appId: '1:472340965151:web:554b9186378141a31db22a',
    messagingSenderId: '472340965151',
    projectId: 'flutterhackathon-f3a03',
    authDomain: 'flutterhackathon-f3a03.firebaseapp.com',
    storageBucket: 'flutterhackathon-f3a03.firebasestorage.app',
  );

}